In [3]:
import pandas as pd

In [41]:
trip_data_7_24= pd.read_csv("202407-bluebikes-tripdata.csv")
stations = pd.read_csv("current_bluebikes_stations.csv", header =1)

In [42]:
trip_data_7_24

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,5FA2A0E02EC53028,classic_bike,2024-07-11 02:07:46.443,2024-07-11 02:20:34.180,Maverick St at Massport Path,A32044,Maverick St at Massport Path,A32044,42.367741,-71.033360,42.367741,-71.033360,member
1,5D49B9B78C826FD5,classic_bike,2024-07-19 14:07:03.620,2024-07-19 14:08:06.530,NCAAA - Walnut Ave at Crawford St,B32027,NCAAA - Walnut Ave at Crawford St,B32027,42.316902,-71.091946,42.316902,-71.091946,member
2,5FEF6FE539C078FB,electric_bike,2024-07-02 09:06:08.296,2024-07-02 09:12:52.886,Medford Sq - Riverside Ave at River St,F32002,Tufts Sq - Main St at Medford St,F32003,42.417680,-71.108055,42.401697,-71.106128,member
3,709B58276144026B,classic_bike,2024-07-30 13:55:16.971,2024-07-30 14:54:55.077,NCAAA - Walnut Ave at Crawford St,B32027,Harvard Square at Mass Ave/ Dunster,M32018,42.316902,-71.091946,42.373268,-71.118579,casual
4,15755F52835908F5,classic_bike,2024-07-18 19:24:45.546,2024-07-18 19:42:54.574,Maverick St at Massport Path,A32044,Addison St at Saratoga St,A32054,42.367741,-71.033360,42.385181,-71.015137,casual
...,...,...,...,...,...,...,...,...,...,...,...,...,...
542617,285618F3AC532F60,classic_bike,2024-07-03 14:30:19.657,2024-07-03 14:39:53.532,Forest Hills,E32010,Stony Brook T Stop,D32041,42.300923,-71.114249,42.316966,-71.104374,casual
542618,BB1350802E4BE16F,classic_bike,2024-07-03 16:49:51.634,2024-07-03 16:57:27.360,Fan Pier,A32000,Surface Rd at India St,A32013,42.353391,-71.044571,42.358155,-71.052163,casual
542619,B0692667B5FF84B5,electric_bike,2024-07-21 11:40:45.950,2024-07-21 11:46:08.678,Forest Hills,E32010,Stony Brook T Stop,D32041,42.300923,-71.114249,42.316966,-71.104374,casual
542620,0159BB19E0AFEBE5,classic_bike,2024-07-07 12:13:41.004,2024-07-07 12:31:03.983,Beacon St at Charles St,D32024,Boylston St at Fairfield St,C32008,42.356052,-71.069849,42.348804,-71.082369,casual
542621,6DE273F8764DCF2A,classic_bike,2024-07-09 18:34:42.761,2024-07-09 19:05:16.811,Beacon St at Charles St,D32024,Harvard University Gund Hall at Quincy St / Ki...,M32021,42.356052,-71.069849,42.376369,-71.114025,casual

In [48]:
stations

,Number,NAME,Lat,Long,Seasonal Status,Municipality,Total Docks,Station ID (to match to historic system data)
0,L32001,Railroad Lot and Minuteman Bikeway,42.416065,-71.153366,Year Round,Arlington,11.0,461
1,L32002,Linwood St at Minuteman Bikeway,42.409354,-71.149065,Year Round,Arlington,11.0,462
2,L32005,Thorndike Field at Minuteman Bikeway,42.400168,-71.144570,Year Round,Arlington,11.0,480
3,L32003,Mass Ave at Grafton St,42.407261,-71.143821,Winter Storage,Arlington,11.0,464
4,L32004,Broadway at Grafton St,42.409942,-71.140093,Winter Storage,Arlington,11.0,465
...,...,...,...,...,...,...,...,...
486,TBD - upcoming install,Arsenal on the Charles,42.363494,-71.164216,NaN,Watertown,NaN,No ID pre-March 2023
487,TBD - upcoming install,Damrell St at Old Colony Ave,42.332397,-71.054415,NaN,Boston,NaN,No ID pre-March 2023
488,TBD - upcoming install,Melnea Cass Blvd at Hampden St,42.330960,-71.075488,NaN,Boston,NaN,No ID pre-March 2023
489,TBD - upcoming install,West Street,42.403517,-71.063277,NaN,Everett,NaN,No ID pre-March 2023
490,TBD - upcoming install,1515 Commonwealth Ave,42.346426,-71.141581,NaN,Boston,NaN,No ID pre-March 2023

In [28]:
''' 
station starts at max capacity -- number of total docks

each time a station is interacted with, retrieve last interaction w station, then:
    subtract 1 each time trip leaves from station 
    add 1 each time trip ends at station 

for each interaction with station, add to column in row current count of bikes in station after interaction has occured

'''

In [ ]:
##iterate thru rows of trips, for start and stop stations, calc bikes in station
def bike_count():
        
## return count

In [62]:
def calc_bike_count(trip_data):
    ## dict of total space in station
    stationDock = dict(zip(stations['NAME'], stations['Total Docks']))
    for ii in range(0, len(trip_data)):
        row = trip_data.iloc[ii]
        start_station = row['start_station_name']
        end_station = row['end_station_name']
        if (start_station not in stationDock):
            stationDock[start_station] = 0
        if (end_station not in stationDock):
            stationDock[end_station] = 0

        stationDock[start_station] -=1
        stationDock[end_station] += 1
        
        trip_data['start_station_capacity'] = stationDock[start_station]
        trip_data['end_station_capacity'] = stationDock[end_station]
        ## get counts for dict
        #stationDock[] = bike_count)start
        #stationDock[] = bike_count (end)
    return stationDock

In [65]:
#print(bike_count('Fan Pier'))
calc_bike_count(trip_data_7_24)

KeyboardInterrupt: